### PR TITLE
Unit Conversion!

### LINKED ISSUE #85: Unit conversion for creating recipes
Implement unit conversion on creating recipes so users can choose a different unit and still have an outputted price.

Estimated Time: 4 Hours

### PR DESCRIPTION
**Pull request by joieng1**
## Developer: John Ieng

Closes #85 

### Pull Request Summary

Implemented unit conversion

### Modifications
`src/app/createIngredient/page.tsx`: use ENUM
`src/app/createRecipe/page.tsx`: implemented unit conversion and modified how recipes are created to database
`src/conversion.ts`: conversion function
`src/database/ingredientSchema.ts`: modified schema
`src/database/recipeSchema.ts`: modified schema
`src/types/unitTypes.ts`: added enum

### Testing Considerations

Created new recipes and ingredients, used unit conversion to create recipes. Verified new objects with database.

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages are understandable
- [x] The developer name is specified
- [x] The summary is completed
- [x] Assign reviewers

### Screenshots/Screencast

https://github.com/joieng1/price-plate/assets/70654142/2f40e31b-67b6-4404-82ba-e17197d3e4eb

### CODE REVIEW

**Comment by justinch4n** [comment]
LFG!!

**Comment by justinch4n** [comment]
LGTM*

**Comment by kailaaquino** [comment]
LOOKS AWESOME THANKS JOHN

**Comment by SilverXer0** [comment]
Absolutely brilliant work, you carried this. Don't know how you managed to get it working, but amazing work!!!!

**Pull request merged**
