### PR TITLE
Merge homepage

### LINKED ISSUE #54: Merge GET request for "Recipes"
Call the GET route for recipes and render them onto the main page (recipe pages).

Estimated Time: 3 hours

### PR DESCRIPTION
**Pull request by justinch4n**
## Developer: Justin Chan

Closes #54

### Pull Request Summary

Managed to merge the GET and the DB

### Modifications

Changed the data displayed on homepage from dummy code to the DB

### Testing Considerations

Tested adding through postman, but need to ensure it still works when recipes are added through add recipe

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages are understandable
- [x] The developer name is specified
- [x] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast
Screen Shot 2024-06-04 at 5 02 25 PM

Screen Shot 2024-06-04 at 5 35 37 PM

Screen Shot 2024-06-04 at 5 02 30 PM

{put screenshots of your change, or even better a screencast displaying the functionality}

### CODE REVIEW

**Comment by joieng1** [comment]
Great work justin, everything looks good to me!

**Comment by kailaaquino** [comment]
Looks good, good job Justin!

**Comment by aarav27** [comment]
Nice job on this. LGTM!

**Comment by SilverXer0** [comment]
Nice work!

**Pull request merged**
