### PR TITLE
Create recipe card

### LINKED ISSUE #6: Create Recipe Card
Based on the Figma UI, create the frontend component for the recipe card. Note that this recipe card should have an autofill (props for each field), and allow users to modify the recipe.
Estimated Time: 5 Hours

Screenshot 2024-05-09 at 3 17 12 PM

### PR DESCRIPTION
**Pull request by SilverXer0**
## Developer: Sharan Krishna

Closes #6 

### Pull Request Summary

Completed the individual recipe card

### Modifications

Added code to page.tsx in the recipe card folder as well as made a CSS file for it

### Testing Considerations

I made it similar to the existing ingredientslist file that Aarav made so we could have some similarity in the website. The scheming can be changed if needed. 

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages are understandable
- [x] The developer name is specified
- [x] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast

Screenshot 2024-05-19 at 6 19 28 PM

### CODE REVIEW

**Comment by SilverXer0** [comment]
I think deployment might have failed for the same reason as the other branch - still not sure how to fix it

**Comment by SilverXer0** [comment]
Remade a PR that deploys

**Comment by aarav27** [comment]
Styling looks clean and matches well with the figma design. Nice that you were able to get through the prop-related deployment issues.

**Comment by justinch4n** [comment]
UI and layout matches the Figma and LGTM! Nice job getting the searchbar working!

**Pull request closed without merging**
