### PR TITLE
Create ingredient page john ieng

### LINKED ISSUE #14: Create Ingredients Page
Estimed time: 5 hours

### PR DESCRIPTION
**Pull request by joieng1**
## Developer: John Ieng

Closes #14 

### Pull Request Summary

Create ingredients page

### Modifications

`src/components/Navbar.tsx`: simple styling changes, removed unused modules
`src/app/createIngredient/page.tsx`: built create ingredients page based on figma, with a few small styling changes. Form utilizes zod for validation checking, and shadcn UI components

### Testing Considerations

Rendered page and made sure form validation and form submission is correct

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages are understandable
- [x] The developer name is specified
- [x] The summary is completed
- [x] Assign reviewers

### Screenshots/Screencast
Screenshot 2024-05-22 at 10 38 12 PM
Screenshot 2024-05-22 at 10 38 21 PM
Screenshot 2024-05-22 at 10 41 08 PM

### CODE REVIEW

**Comment by SilverXer0** [comment]
LGTM. Nice job on the form stuff

**Comment by aarav27** [comment]
Nice job with input validation. LGTM!

**Comment by kailaaquino** [comment]
Looks good, nice work on the units!

**Comment by justinch4n** [comment]
Nice job on validating inputs. Other than adding some stylistic elements like on the FIgma LGTM.

**Pull request merged**
