### PR TITLE
Ingredients page aarav

### LINKED ISSUE #14: Create Ingredients Page
Estimed time: 5 hours

### PR DESCRIPTION
**Pull request by aarav27**
## Developer: Aarav Sharma

Closes #14 

### Pull Request Summary

- Created page that displays user's ingredients

### Modifications

/src/app/ingredients/page.tsx
/src/app/ingredients/ingredients.module.css

### Testing Considerations

Build locally and viewed frontend to make sure everything is working fine

### Pull Request Checklist

- [X] Code is neat, readable, and works
- [X] Comments are appropriate
- [X] The commit messages are understandable
- [X] The developer name is specified
- [X] The summary is completed
- [X] Assign reviewers

### Screenshots/Screencast
Screenshot 2024-05-20 at 3 40 49 PM

### CODE REVIEW

**Comment by joieng1** [comment]
Looks great!

**Review by joieng1 — APPROVED** [review]

**Comment by SilverXer0** [comment]
LGTM!

**Comment by kailaaquino** [comment]
Looks great, matches the prototype well!

**Comment by justinch4n** [comment]
LGTM. I like the added hovering button makes the element change colour.

**Pull request merged**
