### PR TITLE
Completed ingredient card 

### LINKED ISSUE #5: Create Ingredient Card
Based on the Figma UI, create the frontend component of the ingredients card with the respective fields. Note that this ingredients card should have an autofill (props for each field), and allow users to modify the ingredient.
Estimated Time: 3 Hours
Screenshot 2024-05-09 at 3 15 49 PM

### PR DESCRIPTION
**Pull request by SilverXer0**
## Developer: Sharan Krishna

Closes #5 

### Pull Request Summary

Completed the Single Ingredient card page accepting props and a default value for the props if nothing is given. 

### Modifications

Edited IngredientCard/page.tsx and added a CSS file for this folder named ingredientCard.module.css.

### Testing Considerations

Page is created as intended. I let space for the navbar up top, so the boxes may need to be slightly repositioned after that component is added. 

Edited the Page to consider dimension changes, so will react to these properly now. 

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages are understandable
- [x] The developer name is specified
- [x] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast

Screenshot 2024-05-19 at 1 39 48 PM

### CODE REVIEW

**Comment by joieng1** [comment]
Hi Sharan, there seems to be an issue that prevents the app from building correctly, I've attached a screenshot of the deployment logs below.

Screenshot 2024-05-19 at 1 42 06 PM

**Comment by SilverXer0** [comment]
Spent a couple hours... Not sure how to fix it at the current moment.

**Comment by SilverXer0** [comment]
Remade a branch that succeeds in deploying

**Comment by aarav27** [comment]
Glad the deployment issues were fixed. Great job with the styling for this page.

**Comment by justinch4n** [comment]
Layout LGTM! Nice job on the ingredient card.

**Pull request closed without merging**
