### PR TITLE
Backend login aarav

### LINKED ISSUE #31: POST Request and Security for Login
Estimated Time: 3 hours
Actual Time: 6 hours

### PR DESCRIPTION
**Pull request by aarav27**
## Developer: Aarav Sharma

Closes #31 

### Pull Request Summary

Created POST request for the login page
Added api fetch call to frontend
Authentication and authorization
- Checking user entered password with encrypted version in database ( with bcrypt)
- Implemented middleware to generate JSON web token when users login in 
- Implemented middleware to verify user's token for all api requests a user makes when logged in 

### Important Notes
For other API requests created in future (e.g. GET Request to display recipes on home page) 
- Frontend: Get token from local storage and in fetch call, add a authorization header to pass in user token in local storage
- Backend: Call authenticateUser method (which verifies the token) from middleware in API request to validate whether user is allowed to make that request (essentially checks whether they are logged in).
- (I can show you how to do these things. It is fairly simple.)

### Modifications

src/app/api/login/route.ts
src/app/login/page.tsx
src/middleware/auth.ts

### Testing Considerations

Used Postman to test the login post request
Tested login button in frontend
Checked to see if JSON web token was generated and stored

### Pull Request Checklist

- [X] Code is neat, readable, and works
- [X] Comments are appropriate
- [X] The commit messages are understandable
- [X] The developer name is specified
- [X] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast
Screenshot 2024-05-24 at 2 08 56 PM
Screenshot 2024-05-24 at 2 10 55 PM

### CODE REVIEW

**Comment by joieng1** [comment]
Great work, this was hard to implement, thanks for taking it on!

**Comment by SilverXer0** [comment]
Great work! This was a complex task, glad you were able to complete it! LGTM

**Comment by kailaaquino** [comment]
Thank you for taking on such a big task, LGTM

**Comment by justinch4n** [comment]
Thanks for completing the login! It looks good.

**Pull request merged**
