### PR TITLE
Create schemas aarav

### LINKED ISSUE #23: Set Up Database and Create Schemas
Estimated Time: 2hr

### PR DESCRIPTION
**Pull request by aarav27**
## Developer: Aarav Sharma

Closes #23 

### Pull Request Summary

Created schemas to create a database representation for the backend

### Modifications

/src/database/userSchema.ts
/src/database/recipeSchema.ts
/src/database/ingredientSchema.ts

### Testing Considerations

Checked with the professor to ensure our data flow and schemas make sense. No proper testing

### Pull Request Checklist

- [X] Code is neat, readable, and works
- [X] Comments are appropriate
- [X] The commit messages are understandable
- [X] The developer name is specified
- [X] The summary is completed
- [X] Assign reviewers

### Screenshots/Screencast
Screenshot 2024-05-21 at 4 25 59 PM
Screenshot 2024-05-21 at 4 27 26 PM
d-cfecc7c74022">
Screenshot 2024-05-21 at 4 27 42 PM

### CODE REVIEW

**Comment by joieng1** [comment]
Looks great!

**Comment by SilverXer0** [comment]
LGTM... We don't need a pointer in each ingredient to the recipe itself so this should work fine. Great work

**Comment by kailaaquino** [comment]
Great work!

**Comment by justinch4n** [comment]
Looks good!

**Pull request merged**
