### PR TITLE
Login + Signup: Kaila

### LINKED ISSUE #3: Create Login Page
- Make our login page as shown by our figma prototype
- Estimated Time: 2 Hours

### PR DESCRIPTION
**Pull request by kailaaquino**
### Pull Request Summary
Created the login and signup page to reflect figma prototype. 
Includes the login/signup fields and links to the signup or login page 

### Modifications
/src/app/login/page.tsx: added input boxes for username and password
/src/app/login/login.module.css

/src/app/signup/page.tsx: added input boxes for signing up 
/src/app/signup/signup.module.css

### Testing Considerations
I tested it locally using npm run dev and npm run build and everything compiles. 

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages are understandable
- [x] The developer name is specified
- [x] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast

Screenshot 2024-05-22 at 9 39 30 PM

Screenshot 2024-05-22 at 9 40 08 PM

### CODE REVIEW

**Comment by SilverXer0** [comment]
We might have to move the logo a little upward on the sign up page, but LGTM. Good work!

**Comment by joieng1** [comment]
Looks great, gonna merge.

**Comment by aarav27** [comment]
Great job with login and signup pages and matches figma design very well. I edited the styling a bit when implementing backend functionality.

**Comment by justinch4n** [comment]
Might wanna add a more distinct drop shadow to match some of the other pages. Otherwise LGTM

**Pull request merged**
